apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-rs
  template:
    metadata:
      labels:
        app: mariadb-rs
    spec:
      containers:
      - name: mariadb
        image: mariadb
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: mariadb-data-vol 
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: root-db-cred
                key: rootPassword
      volumes:
        - name: mariadb-data-vol
          persistentVolumeClaim:
            claimName: mariadb-data-vol