apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-api
  template:
    metadata:
      labels:
        app: app-api
    spec:
      containers:
      - name: api
        image: rkube01/app-api:v1
        ports:
        - containerPort: 8090
        env:
          - name: RDS_USER
            valueFrom:
              secretKeyRef:
                name: db-cred
                key: appUsername
          - name: RDS_PASS
            valueFrom:
              secretKeyRef:
                name: db-cred
                key: appPassword
          - name: RDS_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: db-cred
                key: appPassword
      volumes:
        - name: mariadb-data-vol
          persistentVolumeClaim:
            claimName: mariadb-data-vol