apiVersion: batch/v1
kind: Job
metadata:
  name: schema-loader
spec:
  template:
    spec:
      containers:
      - name: schema-loader
        image: rkube01/schema-loader:v1
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: root-db-cred
                key: rootPassword
      restartPolicy: Never
  backoffLimit: 4