apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-api.fullname" . }}
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-api
  template:
    metadata:
      labels:
        app: app-api
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: api
        image: rkube01/app-api:{{ .Values.imagetag }}
        ports:
        - containerPort: 8090
        env:
          - name: RDS_USER
            valueFrom:
              secretKeyRef:
                name: {{ include "helm-api.fullname" . }}
                key: appUsername
          - name: RDS_PASS
            valueFrom:
              secretKeyRef:
                name: {{ include "helm-api.fullname" . }}
                key: appPassword
          - name: RDS_ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: {{ include "helm-api.fullname" . }}
                key: dbEndpoint
        readinessProbe:
          tcpSocket:
            port: 8090
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8090
          initialDelaySeconds: 30
          periodSeconds: 10