kind: Service
apiVersion: v1
metadata:
  name: {{ include "sample.fullname" . }}
  namespace: api
spec:
  type: LoadBalancer
  selector:
    app: app-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8090